#/*******************************************************************************
# * Copyright (c) 2020 German Aerospace Center (DLR), Simulation and Software Technology, Germany.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *******************************************************************************/
name: 'Virtual Satellite 4 - Build Decision'
description: 'GitHub Action for making a decision on development, integration or release build same as deployments'
outputs:
  build_type: 
    description: "Build Type which is either"
    value: ${{ steps.get_build_type_decision.outputs.build_type }}
  deploy_type: 
    description: "Deploy Type which is either"
    value: ${{ steps.get_build_type_decision.outputs.deploy_type }}
runs:
  using: "composite"
  steps: 
    - id: get_build_type_decision
      run: |
        echo "--- About to make a build decision"
        source ${{ github.action_path }}/../bash/build_decision.sh
        echo "--- Current Build Decision...  $BUILD_TYPE_DECISION"
        echo "--- Current Deploy Decision... $DEPLOY_TYPE_DECISION"
        echo "build_type=$BUILD_TYPE_DECISION" >> $GITHUB_OUTPUT
        echo "deploy_type=$DEPLOY_TYPE_DECISION" >> $GITHUB_OUTPUT
      shell: bash
      env:
        github_ref: ${{ github.ref }}
        github_base_ref: ${{ github.base_ref }}
        github_event_name: ${{ github.event_name }}