name: 'Virtual Satellite 4 - Build decision'
description: 'GitHub Action for making a decision on development, integration or release build same as deployments'
outputs:
  build_type: 
    description: "Build Type which is either"
    value: ${{ steps.get_build_type_decision.outputs.build_type }}
  deploy_type: 
    description: "Deploy Type which is either"
    value: ${{ steps.get_deploy_type_decision.outputs.deploy_type }}
runs:
  using: "composite"
  steps: 
    - run: $BUILD_TYPE_DECISION="development"
      shell: bash
    #- run: $DEPLOY_TYPE_DECISION="release"
    #  shell: bash
    #- id: get_build_type_decision
    #  run: echo "::set-output name=build_type::$BUILD_TYPE_DECISION"
    #  shell: bash
    #- id: get_deploy_type_decision 
    #  run: echo "::set-output name=deploy_type::$DEPLOY_TYPE_DECISION"
    #  shell: bash