#/*******************************************************************************
# * Copyright (c) 2020 German Aerospace Center (DLR), Simulation and Software Technology, Germany.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *******************************************************************************/
name: 'Virtual Satellite 4 - Build Environment Variable Setup'
description: 'GitHub Action for setting up the build environment for successfully executing virtual satellite workflows'
inputs:
  jdk:
     description: 'Set the JDK version to be used'
     default: '8'
  xvfb:
    desription: 'Set the xvfb option'
    default: ''
  pkgs_file:
    desription: 'file containing additional packages to be installed'
    default: 'apt_packages'
runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/../bash/setup_os.sh ${{ inputs.xvfb }} -p ${{ inputs.pkgs_file }} -j ${{ inputs.jdk }}
      shell: bash
