#/*******************************************************************************
# * Copyright (c) 2020 German Aerospace Center (DLR), Simulation and Software Technology, Germany.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *******************************************************************************/
name: 'Virtual Satellite 4 - Maven Simple Build'
description: 'GitHub Action for calling the maven builds without setting up the environment'
inputs:
  build_job:
    description: 'the job such as (spotbugs|surefire|...)'
    required: true
    default: 'assemble'
  build_profile:
    desription: 'the profile to be build such as (development, integration, release)'
    required: true
    default: 'development'
runs:
  using: "composite"
  steps: 
    - run: |
        echo "--- Starting Maven Build - ${{ inputs.build_job }} - ${{ inputs.build_profile }}"
        ${{ github.action_path }}/../bash/maven_build.sh -j ${{ inputs.build_job }} -p ${{ inputs.build_profile }}
      shell: bash
      env:
          github_sha:  ${{ github.sha }}
     