name: 'Virtual Satellite 4 - Maven Build'
description: 'GitHub Action for calling the maven builds'
inputs:
    job:  # id of input
    description: 'the job such as [spotbugs|surefire|...] to be build'
    required: true
    default: 'assemble'
runs:
  using: "composite"
  steps: 
      # --------------------------------------------
      # Development and Feature branches
      # --------------------------------------------
      - name: Build-Assemble - Development
        run: ./bash/maven_build.sh -j assemble -p development
        if: ${{ !contains(github.ref, 'integration') 
             && !contains(github.base_ref, 'integration') 
             && !contains(github.ref, 'integration_snapshot') 
             && !contains(github.ref, 'development_snapshot') 
             && !contains(github.ref, 'master') 
             && !contains(github.base_ref, 'master')
             && !contains(github.ref, 'Release') }}

      # --------------------------------------------
      # Integration branch
      # --------------------------------------------
      - name: Build-Assemble - Integration
        run: ./bash/maven_build.sh -j assemble -p integration
        if: ${{ github.ref == 'refs/heads/integration' 
             || github.event_name == 'pull_request' && contains(github.base_ref, 'integration')   }}

      # --------------------------------------------
      # Master branch or Release tag
      # --------------------------------------------
      - name: Build-Assemble - Release
        run: ./bash/maven_build.sh -j assemble -p release
        if: ${{ contains(github.ref, 'master') || (contains(github.ref, 'refs/tags/') && contains(github.ref, 'Release')) 
             || github.event_name == 'pull_request' && contains(github.base_ref, 'master')  }}
        env:
          github.sha:  ${{ github.sha }}
    - run: ${{ github.action_path }}/../bash/maven_build.sh ${{ inputs.known_authors }}
      shell: bash
      env:
          base_ref:  ${{ github.base_ref || github.ref }}
          to_repository: ${{ github.repository }}
          from_repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
