name: 'Virtual Satellite 4 - Maven Build'
description: 'GitHub Action for calling the maven builds'
inputs:
  build_job:  # id of input
    description: 'the job such as [spotbugs|surefire|...] to be build'
    required: true
    default: 'assemble'
runs:
  using: "composite"
  steps: 
    # --------------------------------------------
    # Development and Feature branches
    # --------------------------------------------
    - name: Build-Assemble - Development
      run: ./bash/maven_build.sh -j ${{ inputs.job }} -p development
      shell: bash
      if: ${{ !contains(github.ref, 'integration') 
           && !contains(github.base_ref, 'integration') 
           && !contains(github.ref, 'integration_snapshot') 
           && !contains(github.ref, 'development_snapshot') 
           && !contains(github.ref, 'master') 
           && !contains(github.base_ref, 'master')
           && !contains(github.ref, 'Release') }}

    # --------------------------------------------
    # Integration branch
    # --------------------------------------------
    - name: Build-Assemble - Integration
      run: ./bash/maven_build.sh -j ${{ inputs.job }} -p integration
      shell: bash
      if: ${{ github.ref == 'refs/heads/integration' 
          || github.event_name == 'pull_request' && contains(github.base_ref, 'integration')   }}

    # --------------------------------------------
    # Master branch or Release tag
    # --------------------------------------------
    - name: Build-Assemble - Release
      run: ./bash/maven_build.sh -j ${{ inputs.job }} -p release
      shell: bash
      if: ${{ contains(github.ref, 'master') || (contains(github.ref, 'refs/tags/') && contains(github.ref, 'Release')) 
          || github.event_name == 'pull_request' && contains(github.base_ref, 'master')  }}
      env:
        github.sha:  ${{ github.sha }}}
