#/*******************************************************************************
# * Copyright (c) 2020 German Aerospace Center (DLR), Simulation and Software Technology, Germany.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *******************************************************************************/
name: 'Virtual Satellite 4 - Verify Commit Authors'
description: 'GitHub Action for checking that all commits are from authors in a given knwon_authors file'
inputs:
  known_authors:  # id of input
    description: 'known_authors file to be used for the verification'
    required: true
    default: 'knwon_authos.txt'
runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/../bash/verify_commit_authors.sh ${{ inputs.known_authors }}
      shell: bash
      env:
          github_ref: ${{ github.ref }}
          github_base_ref: ${{ github.base_ref }}
          TO_REPOSITORY: ${{ github.ref }}
          github_to_repository: ${{ github.repository }}
          github_event_name: ${{ github.event_name }}
          github_from_repository: ${{ github.event.pull_request.head.repo.full_name }}
          FROM_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name }}
