name: 'Virtual Satellite 4 - Deploy Product'
description: 'GitHub Action for deploying and assembled product to sourceforge and GitHub releases'
inputs:
  build_profile:
    desription: 'the profile to be build such as (development, integration, release)'
    required: true
    default: 'unset'
  gh_token:
    desription: 'the secret token for accessing github releases'
    required: true
    default: 'unset'
runs:
  using: "composite"
  steps: 
    - run: |
        echo "--- About to deploy to GitHub Releases"
        echo "Token: ${{ inputs.gh_token }}"
        #${{ github.action_path }}/../bash/deploy_github_release.sh \
        #  --profile ${{ inputs.build_profile }} \
        #  --token ${{ inputs.gh_token }} \
        #  --ref ${{ github.ref}} \
        #  --repository ${{ github.repository }} \
        #  --sha ${{ github.sha }}
        ${{ github.action_path }}/../bash/github_release_api.sh -t ${{ inputs.gh_token }} -c multi -r "integration_snapshot" -p "EquationEditorDataModel.png" -dir .
      shell: bash
