#/*******************************************************************************
# * Copyright (c) 2020 German Aerospace Center (DLR), Simulation and Software Technology, Germany.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0
# *******************************************************************************/
name: 'Virtual Satellite 4 - Deploy Product GitHub Releases'
description: 'GitHub Action for deploying an assembled product to GitHub Releases'
inputs:
  build_profile:
    desription: 'the profile to be build such as (development, integration, release)'
    required: true
    default: 'unset'
  gh_token:
    desription: 'the secret token for accessing github releases'
    required: true
    default: 'unset'
runs:
  using: "composite"
  steps: 
    - run: |
        echo "--- About to deploy to GitHub Releases"
        ${{ github.action_path }}/../bash/deploy_github_release.sh \
          --profile ${{ inputs.build_profile }} \
          --token ${{ inputs.gh_token }} \
          --ref ${{ github.ref}} \
          --repository ${{ github.repository }} \
          --sha ${{ github.sha }}
      shell: bash
